# Generated by Django 2.2.2 on 2020-01-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('profile_pic', models.ImageField(blank=True, default='defaulprofilepic.pgn', upload_to='profile_pics', verbose_name='تصویر پروفایل')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن همراه')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(max_length=25, verbose_name='نام')),
                ('last_name', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام کاربری')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ملحق شدن')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین ورود')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
    ]
