# Generated by Django 2.2.2 on 2020-01-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('kiri', 'kosher'), ('sammi', 'toxic')], default='sammi', max_length=1),
        ),
    ]
